name: test

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          cache: true
      - run: make test

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force


#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: fetch all tags
#         run: git fetch --force --tags
#       - run: sudo apt-get install gcc-multilib g++-multilib
#       - uses: actions/setup-go@v3
#         with:
#           go-version: 1.18.x
#           cache: true
#       - uses: goreleaser/goreleaser-action@v2
#         with:
#           distribution: goreleaser
#           version: latest
#           args: release --rm-dist
#         env:
#           GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }
